// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for S3cloudfrontInvalidationFunction
 */
export interface S3cloudfrontInvalidationFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/s3cloudfront-invalidation.
 */
export class S3cloudfrontInvalidationFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: S3cloudfrontInvalidationFunctionProps) {
    super(scope, id, {
      description: 'src/s3cloudfront-invalidation.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs14.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/s3cloudfront-invalidation.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}